// const MENU = [
//   {
//     id: "regex",
//     name: "REGEX",
//     desc: "Pattern Matching",
//     folder: "regex",
//     //tasks: автоматически подтягивается из файла
//   },
// ];

// ═══════════════════════════════════════════════════════════════
//  GRID::RUNNER — menu.js
//  Task registry. Each category references files in:
//    grid/{folder}/{file}.js       — task skeleton
//    grid/{folder}/{file}.spec.js  — tests
//    grid/{folder}/{file}.sol.js   — reference solution
//  Icons: grid/{folder}/icon.svg
// ═══════════════════════════════════════════════════════════════

// eslint-disable-next-line no-unused-vars
const MENU = [
  {
    id: "regex",
    name: "REGEX",
    desc: "Pattern Matching",
    folder: "regex",
    tasks: [
      {
        id: "regex_1",
        title: "Remove all words `cat`",
        diff: 2,
        desc: "Remove all occurrences of 'cat' (case-insensitive)",
        file: "ex1",
      },
      {
        id: "regex_2",
        title: "Remove Mr. and Mrs.",
        diff: 3,
        desc: "Remove all Mr. and Mrs. from text",
        file: "ex2",
      },
      {
        id: "regex_3",
        title: "Replace Google variations",
        diff: 4,
        desc: "Replace Google, Goooogle, etc. with Yandex",
        file: "ex3",
      },
      {
        id: "regex_4",
        title: "Mask mid letter",
        diff: 4,
        desc: "Change lel. lil. to l*l. (with dots)",
        file: "ex4",
      },
      {
        id: "regex_5",
        title: "4-letter owners",
        diff: 5,
        desc: "Find 4-letter names of rat/cat owners",
        file: "ex5",
      },
      {
        id: "regex_6",
        title: "Remove 0-5 and Capitals",
        diff: 4,
        desc: "Remove digits 0-5 and uppercase letters",
        file: "ex6",
      },
      {
        id: "regex_7",
        title: "Replace 'the' with 'a'",
        diff: 3,
        desc: "Replace all 'the' and 'The' with 'a'",
        file: "ex7",
      },
      {
        id: "regex_8",
        title: "Validate 'xo' count",
        diff: 5,
        desc: "Check if message contains 'xo' 2 or 3 times",
        file: "ex8",
      },
      {
        id: "regex_9",
        title: "Lines starting with 'The'",
        diff: 4,
        desc: "Count how many lines start with 'The'",
        file: "ex9",
      },
      {
        id: "regex_10",
        title: "Format lol-like words",
        diff: 6,
        desc: "Change lel, lil to l*l, but keep lol",
        file: "ex10",
      },
      {
        id: "regex_11",
        title: "Bills >= $100",
        diff: 6,
        desc: "Count bills that are more than or equal to $100",
        file: "ex11",
      },
      {
        id: "regex_12",
        title: "Bills < $100",
        diff: 6,
        desc: "Count bills that are less than $100",
        file: "ex12",
      },
      {
        id: "regex_13",
        title: "Bills in range",
        diff: 6,
        desc: "Count bills between $100 and $9999",
        file: "ex13",
      },
      {
        id: "regex_14",
        title: "URL to Link",
        diff: 8,
        desc: "Transform social media URLs into HTML anchors",
        file: "ex14",
      },
      {
        id: "regex_15",
        title: "Valid HTML",
        diff: 6,
        desc: "Check if the text is a single valid HTML document",
        file: "ex15",
      },
      {
        id: "regex_16",
        title: "Count JS Comments",
        diff: 7,
        desc: "Count both single line and multi-line comments",
        file: "ex16",
      },
      {
        id: "regex_17",
        title: "Trim &nbsp;",
        diff: 5,
        desc: "Trim non-breaking spaces in the text",
        file: "ex17",
      },
      {
        id: "regex_18",
        title: "Special IP Count",
        diff: 6,
        desc: "Count IP addresses with specific patterns (4+ units)",
        file: "ex18",
      },
      {
        id: "regex_19",
        title: "ASCII Password",
        diff: 6,
        desc: "Check if password consists only of ASCII symbols",
        file: "ex19",
      },
      {
        id: "regex_20",
        title: "Capitalize Headers",
        diff: 8,
        desc: "Make all text within h1-h6 tags CAPITAL",
        file: "ex20",
      },
      {
        id: "regex_21",
        title: "Same Letter Start/End",
        diff: 7,
        desc: "Count words ending with the same letter they start with",
        file: "ex21",
      },
      {
        id: "regex_22",
        title: "Replace <b> tags",
        diff: 6,
        desc: "Replace all <b> tags with BTAG",
        file: "ex22",
      },
      {
        id: "regex_23",
        title: "Exclude 'lol'",
        diff: 6,
        desc: "Find words like lel, lil, lal but NOT lol",
        file: "ex23",
      },
      {
        id: "regex_24",
        title: "Phone Normalizer",
        diff: 7,
        desc: "Transform any phone format to digits only",
        file: "ex24",
      },
      {
        id: "regex_25",
        title: "Lookahead/Behind",
        diff: 7,
        desc: "Extract prices and HTML titles using lookaround",
        file: "ex25",
      },
      {
        id: "regex_26",
        title: "Product Quantifiers",
        diff: 8,
        desc: "Find product counts but omit prices",
        file: "ex26",
      },
      {
        id: "regex_27",
        title: "Digit Count Logic",
        diff: 9,
        desc: "Regex for exactly 3, less than 3, or 3+ digits",
        file: "ex27",
      },
      {
        id: "regex_28",
        title: "Strong Password",
        diff: 9,
        desc: "Complex validation (case, digits, special, length)",
        file: "ex28",
      },
      {
        id: "regex_29",
        title: "Date Format DD/MM/YYYY",
        diff: 7,
        desc: "Find all correct dates in DD/MM/YYYY format",
        file: "ex29",
      },
      {
        id: "regex_30",
        title: "Password Scavenger",
        diff: 9,
        desc: "Find all valid complex passwords in a large text",
        file: "regex_30",
      },
      {
        id: "regex_31",
        title: "HEX Color Picker",
        diff: 6,
        desc: "Find valid HEX codes (#RGB, #RGBA, #RRGGBB, etc.)",
        file: "ex31",
      },
    ],
  },
  {
    id: "algo",
    name: "ALGO",
    desc: "Core Algorithms",
    folder: "algo",
    tasks: [
      {
        id: "algo_1",
        title: "Two Sum",
        diff: 3,
        desc: "Find two indices whose values sum to target",
        file: "algo_1",
      },
      {
        id: "algo_2",
        title: "Fibonacci",
        diff: 4,
        desc: "Return the Nth Fibonacci number (O(n) solution)",
        file: "algo_2",
      },
      {
        id: "algo_3",
        title: "Valid Palindrome",
        diff: 2,
        desc: "Is the string a palindrome? (alphanumeric only)",
        file: "algo_3",
      },
      {
        id: "algo_4",
        title: "Max Subarray",
        diff: 6,
        desc: "Kadane's algorithm — max sum contiguous subarray",
        file: "algo_4",
      },
      {
        id: "algo_5",
        title: "Binary Search",
        diff: 4,
        desc: "Return index of target in sorted array, -1 if none",
        file: "algo_5",
      },
      {
        id: "algo_6",
        title: "Valid Brackets",
        diff: 5,
        desc: "Check if bracket string is valid — (), [], {}",
        file: "algo_6",
      },
    ],
  },
  {
    id: "sort",
    name: "SORT",
    desc: "Sorting Algorithms",
    folder: "sort",
    tasks: [],
  },
  {
    id: "tree",
    name: "TREE",
    desc: "Tree Traversal",
    folder: "tree",
    tasks: [],
  },
  {
    id: "graph",
    name: "GRAPH",
    desc: "Graph Problems",
    folder: "graph",
    tasks: [],
  },
  {
    id: "dp",
    name: "DP",
    desc: "Dynamic Programming",
    folder: "dp",
    tasks: [],
  },
  {
    id: "string",
    name: "STRING",
    desc: "String Manipulation",
    folder: "string",
    tasks: [],
  },
  {
    id: "math",
    name: "MATH",
    desc: "Mathematical Problems",
    folder: "math",
    tasks: [],
  },
  {
    id: "array",
    name: "ARRAY",
    desc: "Array Operations",
    folder: "array",
    tasks: [],
  },
  {
    id: "hash",
    name: "HASH",
    desc: "Hash Map Patterns",
    folder: "hash",
    tasks: [],
  },
  {
    id: "recursion",
    name: "RECURSION",
    desc: "Recursion & Backtrack",
    folder: "recursion",
    tasks: [],
  },
  {
    id: "linked",
    name: "LINKED",
    desc: "Linked List Problems",
    folder: "linked",
    tasks: [],
  },
];
